backend = "xrender";
vsync = false;
use-damage = true;

# Transparency
inactive-opacity = 0.80;
active-opacity = 1;


# Fading
fading = true;
fade-in-step = 0.05;
fade-out-step = 0.05;

# Shadows
shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.5;

shadow-exclude = [
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_FULLSCREEN'",
  "class_g = 'Xfce4-terminal'"
];

fade-exclude = [
  "_NET_WM_STATE@:32a *= '_NET_WM_STATE_FULLSCREEN'",
  "class_g = 'Xfce4-terminal'"
];

unredir-if-possible = true;
unredir-if-possible-exclude = [];

